### ISSUE TITLE
Can't create or join memos.

### ISSUE THREAD

**Issue by SeerSorin** [henry232323/Pesterchum-Discord#10]
GIF: https://imgur.com/QGR8XF0

The 'memo' section of the launcher just generally does nothing. You have to pre-join something with the actual client for it to show up. Then as well, you can join only by double-clicking on it.

**Comment by henry232323** [comment]
Many of the buttons are just decorative to imitate the original Pesterchum client. The join button does need to be fixed, but I won't be supporting creating new memos. You're aware memos are existing servers your client is in, right?

**Comment by SeerSorin** [comment]
> 
> 
> Many of the buttons are just decorative to imitate the original Pesterchum client. The join button does need to be fixed, but I won't be supporting creating new memos. You're aware memos are existing servers your client is in, right?

Aye, didn't know that you weren't adding in some of these features. Just kinda seemed... weird to me honestly, sorry about that!

The only server I'm in I made to test out the memos and joined up with the actual app.

**Comment by henry232323** [comment]
No worries. Unfortunately, I'm not planning on making this a full Discord replacement. This does a lot of the simple work, but can't help you with administration or management of the Discord account, that I think is beyond the scope of the project.

**Comment by SeerSorin** [comment]
That's cool! It'd be a lot of work for a one-man project anyway. It's nice to know the join thing will be fixed though! (no clue if I should close this)
