### ISSUE TITLE
Certain themes make the topbar overlap with itself.

### ISSUE THREAD

**Issue by SeerSorin** [henry232323/Pesterchum-Discord#13]
GIF: https://imgur.com/v0Zjrpx

Things on the top bar where "client" is overlaps with the skin, also included with this bug is the borders on Serious Business are no longer curved.

**Comment by henry232323** [comment]
Hmm, this one is a tough one, I'm not sure I'll be able to fix that due to the limitations on the library but I'll see what I can do.

**Comment by henry232323** [comment]
Unfortunately, the black corners can't actually be removed, which is a limitation of the library. I at least made the menu not overlap
