### ISSUE TITLE
Trying to get this to work... failed to log in.

### ISSUE THREAD

**Issue by shinyjiggly** [henry232323/Pesterchum-Discord#17]
Alright so, I found my token using these instructions https://discordhelp.net/discord-token , since the instructions in the readme seemed to be outdated and pasted it into the box and I got a failed to connect message. 
I'm assuming this client needs to be updated or something? I ran the updater and tried again but got the same result. 
I use windows 10 and I also had discord open on the same machine. The token I got was a hella long alphanumeric string (which I will not share because that's basically asking to be hacked) so I figure I used the right thing.

**Comment by henry232323** [comment]
Ah I think Discord may well have had an update since the last release, I'll investigate this

**Comment by henry232323** [comment]
Check out the newest release :)
