### ISSUE TITLE
Cannot find the 'pesterchum.exe' file

### ISSUE THREAD

**Issue by Niri-hub** [henry232323/Pesterchum-Discord#19]
I have downloaded the file and unzipped it but there appears to be no sign of the 'pesterchum.exe' anywhere in any of the folders. There is a 'pesterchum.py' file but it seems to do nothing

**Comment by henry232323** [comment]
Make sure you're downloading from the releases, not downloading the application source code.
https://github.com/henry232323/Pesterchum-Discord/releases
