### ISSUE TITLE
Memo Issues

### ISSUE THREAD

**Issue by BubblineBee** [henry232323/Pesterchum-Discord#5]
Whenever I change tabs in a memo the userlist disappears and new messages don't appear.
This happens no matter which memo I'm in.

![Picture demonstrating the issue](https://backwards-n.js.org/cards/blank_userlist.PNG)
![Similar picture in different memo](https://backwards-n.js.org/cards/bluser2.PNG)

**Comment by henry232323** [comment]
This is definitely an issue. Unfortunately I don't know that there is anything I can do to fix this. How did you get your user token? This app shouldn't work anymore since Discord make user tokens inaccessible

**Comment by BubblineBee** [comment]
Sorry for the late reply, but I simply followed the instructions you provided in the readme, with the exception that I had to use the filter box to find it.
