### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by softpup** [henry232323/Pesterchum-Discord#6]
After extracting all files and trying to run the Pesterchum executable file i'm presented with an error saying "Python error in main script" and shows me every instance of the find and load command "<frozen importlib_bootstrap>". I'm running windows 10 and my Discord client is fully updated. Any idea how to fix that?

**Comment by henry232323** [comment]
Discord client shouldn't impact it. Can you show me the error text? In any case it is unlikely you will get the client working since Discord intends to ensure that we cannot use 3rd party clients

**Comment by softpup** [comment]
https://imgur.com/a/zIXtHEl here's an image of the error, thank you.

**Comment by softpup** [comment]
https://imgur.com/a/zIXtHEl here's an image of the error, thank you.

**Comment by henry232323** [comment]
Make sure there is a `cfg` folder somewhere in there and that the program has permission to read/write to it
