### ISSUE TITLE
Trouble installing?

### ISSUE THREAD

**Issue by radTad15** [henry232323/Pesterchum-Discord#8]
When I extract the files into a new folder and run "pesterchum.py" it opens the console for a second and then closes immediately. 
There is no "pesterchum.exe" the Install section said there was, so im not really sure what to do.

**Comment by henry232323** [comment]
You don't want to grab the source code. Use the release from the releases tab

**Comment by radTad15** [comment]
Welp, guess whos stupid? As you can probably guess I dont use GitHub all too much so I always have trouble with it lol, thanks man
